// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUVVF_W9-AoV87slZJshD8OZRZlLced0k',
    appId: '1:375138173967:web:18ab85e4913ac974524f7a',
    messagingSenderId: '375138173967',
    projectId: 'carepass-b0220',
    authDomain: 'carepass-b0220.firebaseapp.com',
    storageBucket: 'carepass-b0220.firebasestorage.app',
    measurementId: 'G-QRVD559EW9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUvIUFW3u6hXY1DMJdrRrK2DScOfhc7JQ',
    appId: '1:375138173967:android:50d6e29e7d336884524f7a',
    messagingSenderId: '375138173967',
    projectId: 'carepass-b0220',
    storageBucket: 'carepass-b0220.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQBcI2QnBJw06rziB4AMbZUy6ljGV7bgs',
    appId: '1:375138173967:ios:ea1c8ccceea85093524f7a',
    messagingSenderId: '375138173967',
    projectId: 'carepass-b0220',
    storageBucket: 'carepass-b0220.firebasestorage.app',
    iosBundleId: 'com.example.carepass',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQBcI2QnBJw06rziB4AMbZUy6ljGV7bgs',
    appId: '1:375138173967:ios:ea1c8ccceea85093524f7a',
    messagingSenderId: '375138173967',
    projectId: 'carepass-b0220',
    storageBucket: 'carepass-b0220.firebasestorage.app',
    iosBundleId: 'com.example.carepass',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAUVVF_W9-AoV87slZJshD8OZRZlLced0k',
    appId: '1:375138173967:web:c7952cb49685e724524f7a',
    messagingSenderId: '375138173967',
    projectId: 'carepass-b0220',
    authDomain: 'carepass-b0220.firebaseapp.com',
    storageBucket: 'carepass-b0220.firebasestorage.app',
    measurementId: 'G-XM3KB9K1RT',
  );
}
